---
# opensuse_libdvdcss/tasks/main.yml

- name: 'Add libdvdcss GPG key'
  ansible.builtin.rpm_key:
    state: 'present'
    key: 'https://opensuse-guide.org/repo/openSUSE_Tumbleweed/repodata/repomd.xml.key'

- name: 'Add libdvdcss repository'
  ansible.builtin.template:
    src: 'libdvdcss.repo.j2'
    dest: '/etc/zypp/repos.d/libdvdcss.repo'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Install the libdvdcss package'
  community.general.zypper:
    name: 'libdvdcss2'
    state: 'present'
    disable_recommends: true
    update_cache: true
